resources:
  - name: sample_1
    type: GitRepo
    path: bindushree16/c7
    gitProvider: my_integration
    
pipelines:
  - name: pipeline_1           
    steps:    
      - name: test1
        type: Bash
        execution:
          onExecute:
            - echo "hello"
            

