resources:
  - name: sample_1
    type: gitRepo
    repoPath: bindushree16/c7
    configuration:
      integrationName: github
      branches:
        only: master
      tags:
        except: none
        only: none   
      buildOnCommit: true
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnRelease: true
      buildOnTagPush: true
      buildOnFileCommit: "*test"
      shallowDepth: 2
      gitConfig: 
        - dont_know
        - dont_know_2
    initialVersion:
      sha: master

pipelines:
  - name: pipeline_1
    setup:
      environmentVariables:
        readOnly:
          - ENV1:               
      runtime:       
        type: image
        image:
          auto:
            language:
            versions:
          custom:
            name:
            tag:
            options:
            
    steps:    
      - name: test1
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - sample_1
        execution:
          onExecute:
            - echo "hello"
            
      - name: test2
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16cppall
               tag: master
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - echo "step2"
